[versions]
agp = "8.1.2"
kotlin = "1.9.20"
wire = "4.9.2"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
wire = { id = "com.squareup.wire", version.ref = "wire" }